-- Contents
---- Dropping Tables

----------------------------------------
-- Dropping Tables
----------------------------------------
DECLARE
    tableCount integer;
BEGIN
    SELECT COUNT(1) INTO tableCount FROM USER_TABLES WHERE TABLE_NAME = 'DATABASECHANGELOG'; IF tableCount = 1 THEN EXECUTE IMMEDIATE 'DROP TABLE DATABASECHANGELOG CASCADE CONSTRAINTS PURGE'; END IF;
    SELECT COUNT(1) INTO tableCount FROM USER_TABLES WHERE TABLE_NAME = 'DATABASECHANGELOGLOCK'; IF tableCount = 1 THEN EXECUTE IMMEDIATE 'DROP TABLE DATABASECHANGELOGLOCK CASCADE CONSTRAINTS PURGE'; END IF;
    SELECT COUNT(1) INTO tableCount FROM USER_TABLES WHERE TABLE_NAME = 'TABLE_A'; IF tableCount = 1 THEN EXECUTE IMMEDIATE 'DROP TABLE TABLE_A CASCADE CONSTRAINTS PURGE'; END IF;
    SELECT COUNT(1) INTO tableCount FROM USER_TABLES WHERE TABLE_NAME = 'TABLE_B'; IF tableCount = 1 THEN EXECUTE IMMEDIATE 'DROP TABLE TABLE_B CASCADE CONSTRAINTS PURGE'; END IF;
    SELECT COUNT(1) INTO tableCount FROM USER_TABLES WHERE TABLE_NAME = 'TABLE_C'; IF tableCount = 1 THEN EXECUTE IMMEDIATE 'DROP TABLE TABLE_C CASCADE CONSTRAINTS PURGE'; END IF;
END;
