#!/usr/bin/env bash

LIQUIBASE_HOME=/home/tsxadmin/liquibase-3.5.1-bin
CLASSPATH=/home/tsxadmin/apache-tomcat-8.0.22/webapps/Services-6.13-Release.war
CHANGE_LOG_FILE=changelog/master-changelog.xml
DB_DRIVER=org.hsqldb.jdbc.JDBCDriver
DB_HOST=192.168.105.108
DB_PORT=9001
DB_SID=crdm
DB_URL=jdbc:hsqldb:hsql://$DB_HOST:$DB_PORT/$DB_SID
DB_USERNAME=CRDM
DB_PASSWORD=crdm

"$LIQUIBASE_HOME/liquibase" --classpath=$CLASSPATH --changeLogFile=$CHANGE_LOG_FILE --driver=$DB_DRIVER --url=$DB_URL --username=$DB_USERNAME --password=$DB_PASSWORD update
echo
