@ECHO OFF
SETLOCAL
SET LIQUIBASE_HOME=D:\liquibase-3.5.1-bin
SET CLASSPATH=%LIQUIBASE_HOME%\lib
SET CHANGE_LOG_FILE=../changelogs/changelog-master.xml
SET DATABASE_DRIVER=org.hsqldb.jdbc.JDBCDriver
SET DATABASE_HOST=localhost
SET DATABASE_PORT=9001
SET DATABASE_SID=liquibase
SET DATABASE_URL=jdbc:hsqldb:hsql://%DATABASE_HOST%:%DATABASE_PORT%/%DATABASE_SID%
SET DATABASE_USERNAME=RAYCHEN
SET DATABASE_PASSWORD=a1b2c3d4

CALL "%LIQUIBASE_HOME%\liquibase.bat" --classpath=%CLASSPATH% --changeLogFile=%CHANGE_LOG_FILE% --driver=%DATABASE_DRIVER% --url=%DATABASE_URL% --username=%DATABASE_USERNAME% --password=%DATABASE_PASSWORD% --logLevel=info update
ECHO.

PAUSE
